import { Event, TeamMember, Project, BlogPost, GalleryItem, Stat, Testimonial, FAQ, Sponsor } from "@/types";

export const stats: Stat[] = [
  { label: "Active Members", value: 250, suffix: "+", icon: "users" },
  { label: "Events Hosted", value: 45, suffix: "+", icon: "calendar" },
  { label: "Projects Built", value: 80, suffix: "+", icon: "code" },
  { label: "Hackathons Won", value: 12, suffix: "", icon: "trophy" },
];

export const events: Event[] = [
  {
    id: 1,
    title: "CodeSprint 2024",
    date: "2024-12-15",
    time: "09:00 AM - 06:00 PM",
    venue: "Main Auditorium",
    type: "Hackathon",
    description: "A 9-hour hackathon focused on building innovative solutions for real-world problems. Prizes worth $5000.",
    registrationLink: "#",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&q=80",
    spots: 100,
    registered: 78,
    isPast: false,
  },
  {
    id: 2,
    title: "AI/ML Workshop Series",
    date: "2024-12-20",
    time: "02:00 PM - 05:00 PM",
    venue: "Lab 302",
    type: "Workshop",
    description: "Hands-on workshop covering neural networks, computer vision, and NLP with Python and TensorFlow.",
    registrationLink: "#",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80",
    spots: 50,
    registered: 42,
    isPast: false,
  },
  {
    id: 3,
    title: "Web Dev Bootcamp",
    date: "2025-01-10",
    time: "10:00 AM - 04:00 PM",
    venue: "Online",
    type: "Bootcamp",
    description: "Intensive 3-day bootcamp covering React, Next.js, TypeScript, and modern web development practices.",
    registrationLink: "#",
    image: "https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?w=800&q=80",
    spots: 200,
    registered: 156,
    isPast: false,
  },
  {
    id: 4,
    title: "Cybersecurity Seminar",
    date: "2024-11-10",
    time: "11:00 AM - 01:00 PM",
    venue: "Conference Hall B",
    type: "Seminar",
    description: "Expert-led seminar on ethical hacking, penetration testing, and securing modern web applications.",
    registrationLink: "#",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80",
    spots: 80,
    registered: 80,
    isPast: true,
  },
  {
    id: 5,
    title: "Design Sprint Challenge",
    date: "2024-10-25",
    time: "09:00 AM - 05:00 PM",
    venue: "Design Studio",
    type: "Competition",
    description: "UI/UX design competition where teams create stunning interfaces for given problem statements.",
    registrationLink: "#",
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80",
    spots: 60,
    registered: 55,
    isPast: true,
  },
  {
    id: 6,
    title: "Blockchain Workshop",
    date: "2025-01-25",
    time: "01:00 PM - 04:00 PM",
    venue: "Lab 401",
    type: "Workshop",
    description: "Introduction to blockchain technology, smart contracts, and building DApps with Ethereum.",
    registrationLink: "#",
    image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&q=80",
    spots: 40,
    registered: 28,
    isPast: false,
  },
];

export const teamMembers: TeamMember[] = [
  {
    id: 1,
    name: "Alex Chen",
    role: "President",
    department: "Computer Science",
    year: "Senior",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
    bio: "Full-stack developer passionate about building scalable systems and mentoring junior developers.",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    twitter: "https://twitter.com",
    gradient: "from-blue-500 to-cyan-400",
    isLead: true,
  },
  {
    id: 2,
    name: "Sarah Johnson",
    role: "Vice President",
    department: "Data Science",
    year: "Senior",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80",
    bio: "ML engineer with expertise in NLP and computer vision. Loves hackathons and open source.",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    twitter: "https://twitter.com",
    gradient: "from-purple-500 to-pink-400",
    isLead: true,
  },
  {
    id: 3,
    name: "Marcus Williams",
    role: "Technical Lead",
    department: "Software Engineering",
    year: "Junior",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80",
    bio: "Backend specialist focused on distributed systems and cloud architecture.",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    gradient: "from-emerald-500 to-teal-400",
    isLead: true,
  },
  {
    id: 4,
    name: "Emily Rodriguez",
    role: "Design Lead",
    department: "HCI",
    year: "Junior",
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&q=80",
    bio: "UI/UX designer creating intuitive and beautiful digital experiences.",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    twitter: "https://twitter.com",
    gradient: "from-rose-500 to-orange-400",
    isLead: true,
  },
  {
    id: 5,
    name: "David Kim",
    role: "Events Coordinator",
    department: "Computer Science",
    year: "Sophomore",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80",
    bio: "Organizer extraordinaire. Plans and executes memorable tech events and workshops.",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    gradient: "from-amber-500 to-yellow-400",
    isLead: false,
  },
  {
    id: 6,
    name: "Priya Patel",
    role: "Outreach Lead",
    department: "Information Technology",
    year: "Sophomore",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80",
    bio: "Building bridges between students and industry through partnerships and collaborations.",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    twitter: "https://twitter.com",
    gradient: "from-indigo-500 to-violet-400",
    isLead: false,
  },
  {
    id: 7,
    name: "James Thompson",
    role: "Web Developer",
    department: "Computer Science",
    year: "Freshman",
    image: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=400&q=80",
    bio: "Frontend enthusiast specializing in React and modern CSS frameworks.",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    gradient: "from-sky-500 to-blue-400",
    isLead: false,
  },
  {
    id: 8,
    name: "Lisa Wang",
    role: "ML Engineer",
    department: "Data Science",
    year: "Junior",
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&q=80",
    bio: "Researching deep learning applications in healthcare and autonomous systems.",
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    gradient: "from-fuchsia-500 to-purple-400",
    isLead: false,
  },
];

export const projects: Project[] = [
  {
    id: 1,
    title: "Campus Connect",
    description: "A unified platform for students to discover events, clubs, and resources on campus.",
    tech: ["Next.js", "TypeScript", "PostgreSQL", "Tailwind"],
    github: "https://github.com",
    demo: "https://demo.com",
    stars: 142,
    forks: 38,
    category: "Web",
    contributors: ["Alex Chen", "James Thompson"],
    status: "Active",
  },
  {
    id: 2,
    title: "MediScan AI",
    description: "AI-powered medical image analysis tool for early detection of diseases using computer vision.",
    tech: ["Python", "TensorFlow", "OpenCV", "FastAPI"],
    github: "https://github.com",
    demo: "https://demo.com",
    stars: 89,
    forks: 21,
    category: "AI/ML",
    contributors: ["Sarah Johnson", "Lisa Wang"],
    status: "Active",
  },
  {
    id: 3,
    title: "EcoTrack Mobile",
    description: "Mobile app for tracking carbon footprint and suggesting eco-friendly alternatives.",
    tech: ["React Native", "Firebase", "Node.js"],
    github: "https://github.com",
    demo: "https://demo.com",
    stars: 67,
    forks: 15,
    category: "Mobile",
    contributors: ["Priya Patel", "David Kim"],
    status: "In Progress",
  },
  {
    id: 4,
    title: "StudyBuddy Bot",
    description: "Discord bot that helps students form study groups and manage schedules.",
    tech: ["Node.js", "Discord.js", "MongoDB"],
    github: "https://github.com",
    demo: "https://demo.com",
    stars: 45,
    forks: 12,
    category: "Bot",
    contributors: ["Marcus Williams"],
    status: "Completed",
  },
  {
    id: 5,
    title: "CodeReview Pro",
    description: "Automated code review tool with AI suggestions and security vulnerability detection.",
    tech: ["Python", "AST", "Docker", "Redis"],
    github: "https://github.com",
    demo: "https://demo.com",
    stars: 112,
    forks: 29,
    category: "Web",
    contributors: ["Alex Chen", "Marcus Williams"],
    status: "Active",
  },
  {
    id: 6,
    title: "Smart Campus IoT",
    description: "IoT sensor network for monitoring campus energy usage and optimizing resource allocation.",
    tech: ["Arduino", "MQTT", "InfluxDB", "Grafana"],
    github: "https://github.com",
    demo: "https://demo.com",
    stars: 34,
    forks: 8,
    category: "Other",
    contributors: ["David Kim", "Lisa Wang"],
    status: "In Progress",
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: 1,
    slug: "getting-started-with-machine-learning",
    title: "Getting Started with Machine Learning: A Beginner's Guide",
    excerpt: "Learn the fundamentals of machine learning, from supervised learning to neural networks, with practical examples.",
    content: "Machine learning is a subset of artificial intelligence that enables systems to learn and improve from experience...",
    author: "Sarah Johnson",
    authorRole: "VP & ML Lead",
    authorImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80",
    date: "2024-11-15",
    readTime: "8 min read",
    tags: ["Machine Learning", "AI", "Python"],
    featured: true,
    coverImage: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800&q=80",
  },
  {
    id: 2,
    slug: "building-scalable-apis-with-nextjs",
    title: "Building Scalable APIs with Next.js 14",
    excerpt: "Explore the new App Router and server components to build high-performance APIs in Next.js.",
    content: "Next.js 14 introduces significant improvements to API development...",
    author: "Alex Chen",
    authorRole: "President",
    authorImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
    date: "2024-11-08",
    readTime: "6 min read",
    tags: ["Next.js", "API", "TypeScript"],
    featured: false,
    coverImage: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&q=80",
  },
  {
    id: 3,
    slug: "ui-ux-trends-2025",
    title: "UI/UX Design Trends to Watch in 2025",
    excerpt: "From glassmorphism to AI-generated interfaces, discover the design trends shaping the future.",
    content: "The design landscape is evolving rapidly with new technologies...",
    author: "Emily Rodriguez",
    authorRole: "Design Lead",
    authorImage: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80",
    date: "2024-10-28",
    readTime: "5 min read",
    tags: ["Design", "UI/UX", "Trends"],
    featured: false,
    coverImage: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80",
  },
  {
    id: 4,
    slug: "hackathon-winning-strategies",
    title: "Hackathon Winning Strategies from Our Team",
    excerpt: "Insider tips on ideation, team formation, and presentation from our 12-time hackathon winners.",
    content: "Winning a hackathon requires more than just coding skills...",
    author: "Marcus Williams",
    authorRole: "Technical Lead",
    authorImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80",
    date: "2024-10-15",
    readTime: "7 min read",
    tags: ["Hackathon", "Teamwork", "Strategy"],
    featured: false,
    coverImage: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&q=80",
  },
  {
    id: 5,
    slug: "introduction-to-blockchain",
    title: "Introduction to Blockchain and Smart Contracts",
    excerpt: "A comprehensive guide to understanding blockchain technology and building your first smart contract.",
    content: "Blockchain technology is revolutionizing how we think about trust and decentralization...",
    author: "David Kim",
    authorRole: "Events Coordinator",
    authorImage: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80",
    date: "2024-09-30",
    readTime: "10 min read",
    tags: ["Blockchain", "Ethereum", "Web3"],
    featured: false,
    coverImage: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&q=80",
  },
  {
    id: 6,
    slug: "optimizing-react-performance",
    title: "Optimizing React Performance: Advanced Techniques",
    excerpt: "Deep dive into React optimization patterns including memoization, code splitting, and virtual lists.",
    content: "Performance optimization is crucial for delivering smooth user experiences...",
    author: "James Thompson",
    authorRole: "Web Developer",
    authorImage: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=200&q=80",
    date: "2024-09-20",
    readTime: "9 min read",
    tags: ["React", "Performance", "JavaScript"],
    featured: false,
    coverImage: "https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?w=800&q=80",
  },
];

export const galleryItems: GalleryItem[] = [
  {
    id: 1,
    src: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&q=80",
    title: "CodeSprint 2024",
    category: "Hackathon",
    date: "2024-03-15",
  },
  {
    id: 2,
    src: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80",
    title: "Tech Talk Series",
    category: "Seminar",
    date: "2024-02-20",
  },
  {
    id: 3,
    src: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&q=80",
    title: "AI Workshop",
    category: "Workshop",
    date: "2024-01-18",
  },
  {
    id: 4,
    src: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=800&q=80",
    title: "Team Building",
    category: "Social",
    date: "2024-01-10",
  },
  {
    id: 5,
    src: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80",
    title: "Design Sprint",
    category: "Competition",
    date: "2023-12-05",
  },
  {
    id: 6,
    src: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&q=80",
    title: "Coding Bootcamp",
    category: "Bootcamp",
    date: "2023-11-20",
  },
  {
    id: 7,
    src: "https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=800&q=80",
    title: "Award Ceremony",
    category: "Social",
    date: "2023-11-15",
  },
  {
    id: 8,
    src: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&q=80",
    title: "Project Showcase",
    category: "Hackathon",
    date: "2023-10-28",
  },
  {
    id: 9,
    src: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800&q=80",
    title: "Networking Event",
    category: "Social",
    date: "2023-10-10",
  },
];

export const techStack = [
  "React", "Next.js", "TypeScript", "Node.js", "Python", "TensorFlow",
  "PostgreSQL", "MongoDB", "Docker", "AWS", "Tailwind CSS", "Figma",
  "Git", "GitHub Actions", "Vercel", "Firebase", "Redis", "GraphQL",
];

export const features = [
  {
    title: "Hands-on Workshops",
    description: "Learn cutting-edge technologies through interactive workshops led by industry experts and senior members.",
    icon: "workshop",
  },
  {
    title: "Hackathons",
    description: "Participate in intense coding competitions to build innovative solutions and win exciting prizes.",
    icon: "hackathon",
  },
  {
    title: "Open Source",
    description: "Contribute to real-world projects, build your portfolio, and collaborate with developers worldwide.",
    icon: "opensource",
  },
  {
    title: "Mentorship",
    description: "Get guidance from experienced seniors and industry professionals to accelerate your tech career.",
    icon: "mentorship",
  },
];

export const testimonials: Testimonial[] = [
  {
    id: 1,
    name: "Jessica Lee",
    role: "Software Engineer at Google",
    content: "Joining Elite Club was the best decision I made in college. The hands-on workshops and mentorship helped me land my dream job.",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80",
  },
  {
    id: 2,
    name: "Michael Brown",
    role: "Full Stack Developer",
    content: "The hackathons here are incredible. I learned more in 48 hours than I did in an entire semester of classes.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
  },
  {
    id: 3,
    name: "Amanda Wilson",
    role: "Data Scientist",
    content: "The AI/ML workshops gave me the foundation I needed to pursue a career in data science. The community is incredibly supportive.",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80",
  },
];

export const faqs: FAQ[] = [
  {
    id: 1,
    question: "How can I join Elite Tech Club?",
    answer: "You can join by filling out the application form on our Join page. We review applications at the start of each semester and welcome students from all technical backgrounds.",
  },
  {
    id: 2,
    question: "Do I need prior coding experience?",
    answer: "Not at all! We welcome members at all skill levels, from complete beginners to advanced developers. Our workshops are designed to accommodate everyone.",
  },
  {
    id: 3,
    question: "What kind of events does the club host?",
    answer: "We host a variety of events including hackathons, workshops, bootcamps, seminars, and networking sessions. Check our Events page for the latest schedule.",
  },
  {
    id: 4,
    question: "Are there any membership fees?",
    answer: "No, membership is completely free. We believe in making tech education accessible to all students.",
  },
  {
    id: 5,
    question: "Can I contribute to club projects?",
    answer: "Absolutely! All our projects are open source and we encourage members to contribute. Visit our Projects page to see what we're working on.",
  },
  {
    id: 6,
    question: "How do I get mentorship from senior members?",
    answer: "You can request mentorship through our Join form or reach out to any lead directly. We pair mentors and mentees based on interests and goals.",
  },
];

export const sponsors: Sponsor[] = [
  { id: 1, name: "Google", tier: "Platinum", logo: "https://images.unsplash.com/photo-1573804633927-bfcbcd909ae4?w=200&q=80" },
  { id: 2, name: "Microsoft", tier: "Platinum", logo: "https://images.unsplash.com/photo-1633419461186-7d40a38105ec?w=200&q=80" },
  { id: 3, name: "Amazon", tier: "Gold", logo: "https://images.unsplash.com/photo-1523474253046-8cd2748b5fd2?w=200&q=80" },
  { id: 4, name: "Meta", tier: "Gold", logo: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=200&q=80" },
  { id: 5, name: "Netflix", tier: "Silver", logo: "https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=200&q=80" },
  { id: 6, name: "Spotify", tier: "Silver", logo: "https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=200&q=80" },
];
